--------------------------------------------------------
--  File created - Tuesday-January-23-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STD
--------------------------------------------------------

  CREATE TABLE "PTM"."STD" 
   (	"ID" NUMBER(3,0), 
	"FNAME" VARCHAR2(20 BYTE), 
	"LNAME" VARCHAR2(20 BYTE), 
	"ISSTD" NUMBER(2,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PTM.STD
SET DEFINE OFF;
Insert into PTM.STD (ID,FNAME,LNAME,ISSTD) values (1,'pranangi','mistry',0);
Insert into PTM.STD (ID,FNAME,LNAME,ISSTD) values (2,'jay','mistry',0);
--------------------------------------------------------
--  DDL for Index STD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PTM"."STD_PK" ON "PTM"."STD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STD
--------------------------------------------------------

  ALTER TABLE "PTM"."STD" ADD CONSTRAINT "STD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PTM"."STD" MODIFY ("ISSTD" NOT NULL ENABLE);
  ALTER TABLE "PTM"."STD" MODIFY ("LNAME" NOT NULL ENABLE);
  ALTER TABLE "PTM"."STD" MODIFY ("FNAME" NOT NULL ENABLE);
  ALTER TABLE "PTM"."STD" MODIFY ("ID" NOT NULL ENABLE);
